# Generated by Django 5.2.7 on 2025-10-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW gestion_sede_view AS
            SELECT id, nombre
            FROM gestion_sede;
            """,
            "DROP VIEW IF EXISTS gestion_sede_view;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION create_sede(p_nombre VARCHAR(100))
            RETURNS VOID AS $$
            BEGIN
                INSERT INTO gestion_sede(nombre) VALUES (p_nombre);
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS create_sede(p_nombre VARCHAR(100));"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION update_sede(p_id INTEGER, p_nombre VARCHAR(100))
            RETURNS VOID AS $$
            BEGIN
                UPDATE gestion_sede SET nombre = p_nombre WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS update_sede(p_id INTEGER, p_nombre VARCHAR(100));"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION delete_sede(p_id INTEGER)
            RETURNS VOID AS $$
            BEGIN
                DELETE FROM gestion_sede WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS delete_sede(p_id INTEGER);"
        ),
    ]