# Generated by Django 5.2.7 on 2026-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_fix_token_blacklist_mssql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado_parcial', 'Despachado Parcialmente'), ('despachado', 'Despachado'), ('facturado', 'Facturado')], default='pendiente', max_length=20),
        ),
    ]
