# Generated by Django 5.2.7 on 2025-10-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_sede_db_objects'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW gestion_area_view AS
            SELECT id, nombre, sede_id
            FROM gestion_area;
            """,
            "DROP VIEW IF EXISTS gestion_area_view;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION create_area(p_nombre VARCHAR(100), p_sede_id INTEGER)
            RETURNS VOID AS $$
            BEGIN
                INSERT INTO gestion_area(nombre, sede_id) VALUES (p_nombre, p_sede_id);
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS create_area(p_nombre VARCHAR(100), p_sede_id INTEGER);"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION update_area(p_id INTEGER, p_nombre VARCHAR(100), p_sede_id INTEGER)
            RETURNS VOID AS $$
            BEGIN
                UPDATE gestion_area SET nombre = p_nombre, sede_id = p_sede_id WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS update_area(p_id INTEGER, p_nombre VARCHAR(100), p_sede_id INTEGER);"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION delete_area(p_id INTEGER)
            RETURNS VOID AS $$
            BEGIN
                DELETE FROM gestion_area WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS delete_area(p_id INTEGER);"
        ),
    ]