# Generated by Django 5.2.10 on 2026-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
