# Generated by Django 5.2.7 on 2025-11-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmovement',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='gestion.producto'),
        ),
    ]
