# Generated by Django 5.2.7 on 2025-11-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_materialmovement_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='location',
            field=models.CharField(default='Ubicación no especificada', max_length=100),
        ),
        migrations.AddField(
            model_name='sede',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
