# Generated by Django 5.2.7 on 2025-10-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_area_db_objects'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW gestion_customuser_view AS
            SELECT id, username, first_name, last_name, email, is_staff, is_active, date_joined, sede_id, area_id
            FROM gestion_customuser;
            """,
            "DROP VIEW IF EXISTS gestion_customuser_view;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION update_user(
                p_id INTEGER,
                p_first_name VARCHAR(150),
                p_last_name VARCHAR(150),
                p_email VARCHAR(254),
                p_sede_id INTEGER,
                p_area_id INTEGER
            )
            RETURNS VOID AS $$
            BEGIN
                UPDATE gestion_customuser
                SET first_name = p_first_name,
                    last_name = p_last_name,
                    email = p_email,
                    sede_id = p_sede_id,
                    area_id = p_area_id
                WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION IF EXISTS update_user(
                p_id INTEGER,
                p_first_name VARCHAR(150),
                p_last_name VARCHAR(150),
                p_email VARCHAR(254),
                p_sede_id INTEGER,
                p_area_id INTEGER
            );"""
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION delete_user(p_id INTEGER)
            RETURNS VOID AS $$
            BEGIN
                UPDATE gestion_customuser SET is_active = false WHERE id = p_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS delete_user(p_id INTEGER);"
        ),
    ]