# Generated by Django 5.2.17 on 2026-09-02 18:01
# Fase 5.1 del barrido de higiene (2026-09-02): modelo nuevo + migración de
# datos que precarga la equivalencia de referencia (1 baño = 15 fundas = 225
# conos) para cada sede existente, requerido por CLAUDE.md ("configurable
# reference examples per sede, not system-wide hardcoded constants").

import django.db.models.deletion
from django.db import migrations, models


def precargar_configuracion_por_sede_existente(apps, schema_editor):
    """
    Crea una ConfiguracionEmpaqueSede (15 fundas/baño, 15 conos/funda — los
    valores que antes estaban hardcodeados sin excepción en
    LoteProduccion.clean() y MRPEngine) para cada Sede ya existente.
    Sedes creadas DESPUÉS de esta migración no necesitan una fila propia: el
    código que lee ConfiguracionEmpaqueSede cae al mismo valor de referencia
    si no encuentra ninguna (ver gestion/models/produccion.py::LoteProduccion.clean
    y inventory/services/mrp_engine.py::MRPEngine._get_conos_por_bano).
    """
    Sede = apps.get_model('gestion', 'Sede')
    ConfiguracionEmpaqueSede = apps.get_model('gestion', 'ConfiguracionEmpaqueSede')
    for sede in Sede.objects.all():
        ConfiguracionEmpaqueSede.objects.get_or_create(
            sede=sede,
            defaults={'fundas_por_bano': 15, 'conos_por_funda': 15},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_pedidoventa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpaqueSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundas_por_bano', models.PositiveIntegerField(default=15, help_text='Equivalencia de referencia: 1 baño = N fundas')),
                ('conos_por_funda', models.PositiveIntegerField(default=15, help_text='Equivalencia de referencia: 1 funda = N conos')),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_empaque', to='gestion.sede')),
            ],
            options={
                'verbose_name': 'Configuración de Empaque por Sede',
                'verbose_name_plural': 'Configuraciones de Empaque por Sede',
            },
        ),
        migrations.RunPython(
            precargar_configuracion_por_sede_existente,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
