# Generated by Django 5.2.7 on 2026-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_calidad_producto_pais_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiene_beneficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='esta_pagado',
            field=models.BooleanField(default=False),
        ),
    ]
