# Generated by Django 5.2.17 on 2026-09-02 19:02
# Barrido de higiene, ítem [DECISIÓN REQUERIDA] confirmado por Brandon
# (2026-09-02): ConsumoLoteDetalle.revertir() adivinaba la bodega a restaurar
# con StockBodega.objects.get(lote=...), lo que falla si ese lote tiene stock
# en más de una bodega — caso frecuente por reprocesos (el mismo lote se
# mueve entre áreas/bodegas). Ambos campos nullable a propósito: no hay forma
# confiable de reconstruir la bodega/producto exactos de las filas ya
# existentes (creadas antes de que consumir() empezara a guardar este dato) —
# sin migración de datos, revertir() cae al comportamiento anterior
# (best-effort) solo para esas filas legacy.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_configuracion_empaque_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumolotedetalle',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.bodega', verbose_name='Bodega del stock consumido'),
        ),
        migrations.AddField(
            model_name='consumolotedetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.producto', verbose_name='Producto del stock consumido'),
        ),
    ]
