# Generated by Django 5.2.7 on 2026-01-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_saldo_pendiente_cliente_tiene_beneficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bodegas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='gestion.bodega'),
        ),
    ]
