# Generated by Django 5.2.7 on 2025-10-16 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_user_db_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='superior',
            field=models.ManyToManyField(blank=True, related_name='inferiors_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
