# Generated by Django 5.2.9 on 2026-01-30 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_customuser_bodegas_asignadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_bulto', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.loteproduccion')),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='gestion.pedidoventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
