# Generated by Django 5.2.7 on 2026-09-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_consumo_lote_detalle_bodega_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
