# Generated by custom request

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group_names = [
        'operario', 
        'bodeguero', 
        'vendedor', 
        'jefe_area', 
        'jefe_planta', 
        'admin_sede', 
        'ejecutivo', 
        'admin_sistemas'
    ]
    
    for name in group_names:
        Group.objects.get_or_create(name=name)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group_names = [
        'operario', 
        'bodeguero', 
        'vendedor', 
        'jefe_area', 
        'jefe_planta', 
        'admin_sede', 
        'ejecutivo', 
        'admin_sistemas'
    ]
    # Only delete if we want to reverse this migration (usually we might leave them, but for completeness)
    Group.objects.filter(name__in=group_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_customuser_bodegas_asignadas'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
