# Generated by Django 5.2.7 on 2026-09-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_batch_dead_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('hilo', 'Hilo'), ('tela', 'Tela'), ('subproducto', 'Subproducto'), ('quimico', 'Químico'), ('insumo', 'Insumo'), ('materia_prima', 'Materia prima'), ('producto_intermedio', 'Producto Intermedio')], max_length=20),
        ),
    ]
