# Generated by Django 5.2.7 on 2025-11-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_materialmovement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='gestion.bodega'),
        ),
    ]
