# Generated by Django 5.2.7 on 2026-09-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_add_producto_intermedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='materia_prima_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_derivados', to='gestion.materiaprimalote', verbose_name='Lote de Materia Prima Origen'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_producidos', to='gestion.producto', verbose_name='Producto del Lote'),
        ),
    ]
