# Generated by Django 5.2.7 on 2025-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_ordenproduccion_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
