# Generated by Django 5.2.11 on 2026-02-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_cliente_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
