# Generated by Django 5.2.7 on 2026-09-17 19:59

import django.db.models.deletion
import gestion.models.core
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_add_lote_producto_and_materia_prima'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('modalidad', models.CharField(choices=[('CONTINUA', 'Producción Continua'), ('STOCK', 'Producción Contra Stock'), ('PEDIDO', 'Producción Bajo Pedido')], db_index=True, default='CONTINUA', max_length=20, verbose_name='Modalidad Productiva')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno Productivo')),
                ('fecha_jornada', models.DateField(db_index=True, verbose_name='Fecha de Jornada')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], db_index=True, default='en_proceso', max_length=20, verbose_name='Estado de la Corrida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_produccion', to='gestion.area', verbose_name='Área Productiva')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_produccion', to='gestion.lineaproduccion', verbose_name='Línea de Producción')),
                ('maquina_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_produccion', to='gestion.maquina', verbose_name='Máquina Principal')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_mes', to='gestion.ordenproduccion', verbose_name='Orden de Producción Asociada')),
                ('pedido_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_mes', to='gestion.pedidoventa', verbose_name='Pedido Comercial Asociado')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_produccion', to='gestion.sede', verbose_name='Sede')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsable')),
            ],
            options={
                'verbose_name': 'Corrida de Producción',
                'verbose_name_plural': 'Corridas de Producción',
                'ordering': ['-fecha_jornada', '-hora_inicio'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperacionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.PositiveIntegerField(default=1, verbose_name='Número de Secuencia')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('en_curso', 'En Curso'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('revertida', 'Revertida')], db_index=True, default='en_curso', max_length=20, verbose_name='Estado de la Operación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('motivo_reversion', models.TextField(blank=True, help_text='Justificación obligatoria en caso de anulación o reversión de inventarios.', null=True, verbose_name='Motivo de Reversión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='gestion.corridaproduccion', verbose_name='Corrida de Producción')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_mes', to='gestion.maquina', verbose_name='Máquina Empleada')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_mes_operadas', to=settings.AUTH_USER_MODEL, verbose_name='Operario Responsable')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_mes', to='gestion.processstep', verbose_name='Paso de Proceso')),
            ],
            options={
                'verbose_name': 'Operación de Producción',
                'verbose_name_plural': 'Operaciones de Producción',
                'ordering': ['corrida', 'numero_secuencia'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MermaDesperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_merma', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso de Merma (kg)')),
                ('tipo_merma', models.CharField(choices=[('maquina', 'Falla Técnica / Máquina'), ('material', 'Defecto de Material / Hilo'), ('setup', 'Arranque / Setup'), ('corte', 'Desperdicio de Corte / Empalme'), ('humedad', 'Pérdida por Humedad / Volatilización'), ('otro', 'Otro Desperdicio')], default='maquina', max_length=30, verbose_name='Tipo de Merma')),
                ('es_subproducto_vendible', models.BooleanField(default=False, help_text='Indica si esta merma ingresa a inventario como subproducto recuperable/vendible.', verbose_name='¿Es Subproducto Vendible?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega_subproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_como_subproducto', to='gestion.bodega', verbose_name='Bodega Destino del Subproducto')),
                ('lote_subproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_subproducto_lote', to='gestion.loteproduccion', verbose_name='Lote Asignado al Subproducto')),
                ('producto_subproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_como_subproducto', to='gestion.producto', verbose_name='Producto Subproducto')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='gestion.operacionproduccion', verbose_name='Operación de Producción')),
            ],
            options={
                'verbose_name': 'Merma y Desperdicio',
                'verbose_name_plural': 'Mermas y Desperdicios',
                'ordering': ['operacion', 'id'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GenealogiaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_padre_usada', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad del Padre Usada (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lote_hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aristas_padres', to='gestion.loteproduccion', verbose_name='Lote Hijo (Producido)')),
                ('lote_padre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aristas_hijos', to='gestion.loteproduccion', verbose_name='Lote Padre (Insumo)')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogias', to='gestion.operacionproduccion', verbose_name='Operación que ejecutó la transformación')),
            ],
            options={
                'verbose_name': 'Genealogía de Lote',
                'verbose_name_plural': 'Genealogías de Lotes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad Consumida')),
                ('costo_unitario', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Costo Unitario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mes', to='gestion.bodega', verbose_name='Bodega de Origen')),
                ('lote_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mes', to='gestion.loteproduccion', verbose_name='Lote de Origen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mes', to='gestion.producto', verbose_name='Producto Consumido')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion.operacionproduccion', verbose_name='Operación de Producción')),
            ],
            options={
                'verbose_name': 'Consumo de Material',
                'verbose_name_plural': 'Consumos de Materiales',
                'ordering': ['operacion', 'id'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProduccionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_neta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad Neta Producida')),
                ('clasificacion_calidad', models.CharField(choices=[('primera', 'Primera Calidad'), ('segunda', 'Segunda Calidad'), ('saldo', 'Saldo / Retazo')], default='primera', max_length=20, verbose_name='Clasificación de Calidad')),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Peso Bruto')),
                ('tara', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Tara')),
                ('unidades_empaque', models.PositiveIntegerField(default=1, verbose_name='Unidades por Empaque')),
                ('cantidad_metros', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Metros Producidos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mes', to='gestion.bodega', verbose_name='Bodega de Destino')),
                ('lote_generado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mes', to='gestion.loteproduccion', verbose_name='Lote Generado')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='gestion.operacionproduccion', verbose_name='Operación de Producción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mes', to='gestion.producto', verbose_name='Producto Resultante')),
            ],
            options={
                'verbose_name': 'Salida de Producción',
                'verbose_name_plural': 'Salidas de Producción',
                'ordering': ['operacion', 'id'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='corridaproduccion',
            index=models.Index(fields=['sede', 'estado'], name='idx_corrida_sede_estado'),
        ),
        migrations.AddIndex(
            model_name='corridaproduccion',
            index=models.Index(fields=['fecha_jornada', 'turno'], name='idx_corrida_jornada_turno'),
        ),
        migrations.AddIndex(
            model_name='corridaproduccion',
            index=models.Index(fields=['modalidad', 'estado'], name='idx_corrida_mod_estado'),
        ),
        migrations.AddConstraint(
            model_name='corridaproduccion',
            constraint=models.UniqueConstraint(fields=('sede', 'codigo'), name='gestion_corridaproduccion_unique_sede_codigo'),
        ),
        migrations.AddIndex(
            model_name='operacionproduccion',
            index=models.Index(fields=['corrida', 'estado'], name='idx_operacion_corrida_estado'),
        ),
        migrations.AddIndex(
            model_name='operacionproduccion',
            index=models.Index(fields=['maquina', 'hora_inicio'], name='idx_operacion_maq_inicio'),
        ),
        migrations.AddConstraint(
            model_name='operacionproduccion',
            constraint=models.UniqueConstraint(fields=('corrida', 'numero_secuencia'), name='gestion_operacionproduccion_unique_corrida_secuencia'),
        ),
        migrations.AddIndex(
            model_name='mermadesperdicio',
            index=models.Index(fields=['operacion', 'tipo_merma'], name='idx_merma_op_tipo'),
        ),
        migrations.AddConstraint(
            model_name='mermadesperdicio',
            constraint=models.CheckConstraint(condition=models.Q(('peso_merma__gte', 0)), name='gestion_mermadesperdicio_peso_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='genealogialote',
            index=models.Index(fields=['lote_padre', 'lote_hijo'], name='idx_genealogia_padre_hijo'),
        ),
        migrations.AddIndex(
            model_name='genealogialote',
            index=models.Index(fields=['lote_hijo', 'lote_padre'], name='idx_genealogia_hijo_padre'),
        ),
        migrations.AddConstraint(
            model_name='genealogialote',
            constraint=models.UniqueConstraint(fields=('lote_padre', 'lote_hijo', 'operacion'), name='gestion_genealogialote_unique_padre_hijo_op'),
        ),
        migrations.AddConstraint(
            model_name='genealogialote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_padre_usada__gt', 0)), name='gestion_genealogialote_cantidad_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='consumomaterial',
            index=models.Index(fields=['operacion', 'producto'], name='idx_consumo_op_prod'),
        ),
        migrations.AddIndex(
            model_name='consumomaterial',
            index=models.Index(fields=['lote_origen'], name='idx_consumo_lote_origen'),
        ),
        migrations.AddConstraint(
            model_name='consumomaterial',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_consumida__gt', 0)), name='gestion_consumomaterial_cantidad_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='produccionsalida',
            index=models.Index(fields=['operacion', 'producto'], name='idx_salida_op_prod'),
        ),
        migrations.AddIndex(
            model_name='produccionsalida',
            index=models.Index(fields=['lote_generado'], name='idx_salida_lote_gen'),
        ),
        migrations.AddConstraint(
            model_name='produccionsalida',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_neta__gt', 0)), name='gestion_produccionsalida_cantidad_gt_zero'),
        ),
    ]
