# Generated by Django 5.2.11 on 2026-02-11 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_producto_precio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='tara',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='unidades_empaque',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='vendedor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('hilo', 'Hilo'), ('tela', 'Tela'), ('subproducto', 'Subproducto'), ('quimico', 'Químico'), ('insumo', 'Insumo')], max_length=20),
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, help_text='Capacidad máxima de producción por turno (ej. kg)', max_digits=10)),
                ('eficiencia_ideal', models.DecimalField(decimal_places=2, help_text='Eficiencia ideal (0.00 a 1.00)', max_digits=3)),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('mantenimiento', 'Mantenimiento'), ('inactiva', 'Inactiva')], default='operativa', max_length=20)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area')),
            ],
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_producidos', to='gestion.maquina'),
        ),
    ]
