# Generated by Django 5.2.7 on 2025-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_ordenproduccion_inventario_descontado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmovement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='from_area',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='from_sede',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='process_step',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='to_area',
        ),
        migrations.RemoveField(
            model_name='materialmovement',
            name='to_sede',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MaterialMovement',
        ),
    ]
