# Generated by Django 5.2.7 on 2025-10-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_batch_db_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.material')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede')),
            ],
            options={
                'unique_together': {('material', 'sede', 'area')},
            },
        ),
    ]
