# Generated by Django 5.2.7 on 2026-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_corridaproduccion_operacionproduccion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordenproduccion',
            name='gestion_ordenproduccion_peso_neto_positivo',
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='peso_neto_requerido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso requerido en kg. Opcional en producción continua o batches abiertos.', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('peso_neto_requerido__gt', 0), ('peso_neto_requerido__isnull', True), _connector='OR'), name='gestion_ordenproduccion_peso_neto_positivo'),
        ),
    ]
