# Generated by Django 5.2.7 on 2026-09-17 20:31

import django.db.models.deletion
import gestion.models.core
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_ordenproduccion_gestion_ordenproduccion_peso_neto_positivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_planificada', models.DecimalField(decimal_places=4, help_text='Cantidad meta a producir (kg o m)', max_digits=12, verbose_name='Cantidad Planificada')),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total producido acumulado (primera + segunda)', max_digits=12, verbose_name='Cantidad Ejecutada')),
                ('cantidad_aceptada', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total conforme de primera calidad', max_digits=12, verbose_name='Cantidad Aceptada')),
                ('cantidad_segunda', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total de segunda calidad', max_digits=12, verbose_name='Cantidad Segunda')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('sobreproducido', 'Sobreproducido')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado del Detalle')),
                ('producto_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_plan_produccion', to='gestion.producto', verbose_name='Producto Objetivo')),
            ],
            options={
                'verbose_name': 'Detalle de Plan de Producción',
                'verbose_name_plural': 'Detalles de Planes de Producción',
            },
        ),
        migrations.AddField(
            model_name='corridaproduccion',
            name='detalle_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_mes', to='gestion.detalleplanproduccion', verbose_name='Detalle de Plan Asociado'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='detalle_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='gestion.detalleplanproduccion', verbose_name='Detalle de Plan de Producción'),
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Plan')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(db_index=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_produccion', to='gestion.sede', verbose_name='Sede')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor / Planificador')),
            ],
            options={
                'verbose_name': 'Plan de Producción',
                'verbose_name_plural': 'Planes de Producción',
                'ordering': ['-fecha_inicio', '-id'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='detalleplanproduccion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.planproduccion', verbose_name='Plan de Producción'),
        ),
        migrations.AddField(
            model_name='corridaproduccion',
            name='plan_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_mes', to='gestion.planproduccion', verbose_name='Plan de Producción Asociado'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='plan_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='gestion.planproduccion', verbose_name='Plan de Producción'),
        ),
        migrations.AddConstraint(
            model_name='planproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='chk_plan_produccion_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.UniqueConstraint(fields=('plan', 'producto_objetivo'), name='uniq_detalle_plan_producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_planificada__gt', 0)), name='chk_detplan_cant_plan_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_ejecutada__gte', 0)), name='chk_detplan_cant_ejec_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_aceptada__gte', 0)), name='chk_detplan_cant_acep_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_segunda__gte', 0)), name='chk_detplan_cant_seg_gte_0'),
        ),
    ]
