# Generated by Django 5.2.11 on 2026-02-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_pagocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_fin_planificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_inicio_planificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='maquina_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='gestion.maquina'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
