# Generated by Django 5.2.11 on 2026-02-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_ordenproduccion_fecha_fin_planificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='operario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
