# Generated by Django 5.2.7 on 2026-09-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_detalleplanproduccion_corridaproduccion_detalle_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad_fabricada',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Cantidad completada en planta para este ítem de pedido', max_digits=12, verbose_name='Cantidad Fabricada'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='estado_fabricacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('fabricado', 'Fabricado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado de Fabricación'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='pedido_venta_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_reservados', to='gestion.pedidoventa', verbose_name='Pedido Reservado (MTO)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='detalle_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='gestion.detallepedido', verbose_name='Detalle de Pedido Comercial'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='pedido_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='gestion.pedidoventa', verbose_name='Pedido Comercial Asociado'),
        ),
    ]
