# Generated by Django 5.2.11 on 2026-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_ordenproduccion_operario_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='gestion.area'),
        ),
    ]
