# Generated by Django 5.2.7 on 2025-10-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_processstep_db_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('transfer', 'Transfer')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='gestion.batch')),
                ('from_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_out_area', to='gestion.area')),
                ('from_sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_out_sede', to='gestion.sede')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to='gestion.processstep')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to=settings.AUTH_USER_MODEL)),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_in_area', to='gestion.area')),
                ('to_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_in_sede', to='gestion.sede')),
            ],
        ),
    ]
