# Generated by Django 5.2.11 on 2026-02-18 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_ordenproduccion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='operarios',
            field=models.ManyToManyField(blank=True, related_name='maquinas_asignadas_control', to=settings.AUTH_USER_MODEL),
        ),
    ]
