# Generated by Django 5.2.17 on 2026-09-25 00:00

import django.core.validators
import django.db.models.deletion
import gestion.models.core
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_procesos_tintoreria'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('motivo', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'El motivo debe tener al menos 10 caracteres.')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_oficial', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_formula_creadas', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='gestion.formulacolor')),
            ],
            options={
                'verbose_name': 'Version de Formula',
                'verbose_name_plural': 'Versiones de Formula',
                'ordering': ['formula', '-numero'],
            },
            bases=(gestion.models.core.SedeResolvableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='version_formula',
            field=models.ForeignKey(blank=True, help_text='Versión de la fórmula congelada al lanzar la orden', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='gestion.versionformula'),
        ),
        migrations.AddConstraint(
            model_name='versionformula',
            constraint=models.UniqueConstraint(condition=models.Q(('es_oficial', True)), fields=('formula',), name='gestion_versionformula_una_oficial_por_formula'),
        ),
        migrations.AlterUniqueTogether(
            name='versionformula',
            unique_together={('formula', 'numero')},
        ),
    ]
