# Generated by Django 5.2.7 on 2025-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_materialmovement_db_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=50)),
            ],
        ),
    ]
