# Generated by Django 5.2.17 on 2026-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_versionado_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='litros_bano',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Litros de baño fijados por el ingeniero tintorero para esta orden.', max_digits=10, null=True),
        ),
    ]
