# Generated by Django 5.2.11 on 2026-02-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_create_seller_reporting_sps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plazo_credito_dias',
            field=models.IntegerField(default=0, help_text='Días de crédito (0=Contado)'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='incluye_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='current_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleformula',
            name='gramos_por_kilo',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='peso_neto_producido',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='tara',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagocliente',
            name='monto',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
