# Generated by Django 5.2.17 on 2026-09-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_orden_litros_bano'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacolor',
            name='es_laboratorio',
            field=models.BooleanField(default=False, help_text='Fórmula de ensayo de laboratorio, no destinada a producción (D8). Se filtra fuera del listado por defecto.'),
        ),
        migrations.AddField(
            model_name='formulacolor',
            name='formula_origen',
            field=models.ForeignKey(blank=True, help_text='Fórmula de la que se importó la receta, si esta es una derivada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='gestion.formulacolor'),
        ),
        migrations.AddField(
            model_name='formulacolor',
            name='motivo_derivacion',
            field=models.TextField(blank=True, default='', help_text='Por qué se derivó esta fórmula de su origen.'),
        ),
        migrations.AddField(
            model_name='formulacolor',
            name='version_origen',
            field=models.ForeignKey(blank=True, help_text='Versión concreta (oficial o ensayo) de la que se copió la receta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas_desde_aqui', to='gestion.versionformula'),
        ),
        migrations.AddField(
            model_name='versionformula',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
