# Generated by Django 5.2.7 on 2025-10-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_chemical_db_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chemical')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.formula')),
            ],
            options={
                'unique_together': {('formula', 'chemical')},
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='chemicals',
            field=models.ManyToManyField(through='gestion.FormulaChemical', to='gestion.chemical'),
        ),
    ]
