# Generated by Django 5.2.11 on 2026-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_add_credit_terms_and_due_date'),
    ]

    operations = [
    ]
