# Generated by Django 5.2.12 on 2026-03-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_update_seller_reporting_sps_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_envio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='formulacolor',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Observaciones generales sobre la formula', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagocliente',
            name='notas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunSQL(
            sql="""
            IF NOT EXISTS (
                SELECT 1 FROM sys.indexes
                WHERE name = N'idx_pedido_vendedor_fecha_incl'
                AND object_id = OBJECT_ID(N'dbo.gestion_pedidoventa')
            )
            BEGIN
                CREATE NONCLUSTERED INDEX idx_pedido_vendedor_fecha_incl
                ON dbo.gestion_pedidoventa (vendedor_asignado_id, fecha_pedido)
                INCLUDE (cliente_id, estado);
            END
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_pedido_vendedor_fecha_incl ON dbo.gestion_pedidoventa;",
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('limite_credito__gte', 0)), name='gestion_cliente_limite_credito_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='gestion_detallepedido_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='gestion_detallepedido_precio_unitario_positivo'),
        ),
        migrations.AddConstraint(
            model_name='loteproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('peso_neto_producido__gte', 0)), name='gestion_loteproduccion_peso_neto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='loteproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('peso_bruto__gte', 0)), name='gestion_loteproduccion_peso_bruto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='loteproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('tara__gte', 0)), name='gestion_loteproduccion_tara_positiva'),
        ),
    ]
