# Generated by Django 5.2.12 on 2026-03-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_update_seller_reporting_sps_iva'),
        ('gestion', '0022_update_seller_reporting_sps_iva'),
    ]

    operations = [
    ]
