# Generated by Django 5.2.12 on 2026-03-10 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion', '0023_detallepedido_subtotal_detallepedido_total_con_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulacolor',
            name='productos',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='FaseReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('pre_tratamiento', 'Pre-Tratamiento / Blanqueo'), ('tintura', 'Tintura Principal'), ('lavado', 'Lavado / Jabonado'), ('suavizado', 'Suavizado / Acabado Final'), ('auxiliares', 'Baño de Auxiliares Extras')], max_length=50)),
                ('orden', models.PositiveIntegerField(help_text='Orden de ejecución del baño dentro del proceso de tintura')),
                ('temperatura', models.PositiveIntegerField(blank=True, help_text='Temperatura objetivo en °C para esta fase (Curva térmica)', null=True)),
                ('tiempo', models.PositiveIntegerField(blank=True, help_text='Tiempo de retención en minutos del baño', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='gestion.formulacolor')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('formula', 'orden')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='detalleformula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detalleformula',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.fasereceta'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleformula',
            unique_together={('fase', 'producto')},
        ),
        migrations.RemoveField(
            model_name='detalleformula',
            name='formula_color',
        ),
    ]
