# Generated by Django 5.2.7 on 2026-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_remove_formulacolor_productos_auditlog_fasereceta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='cantidad_metros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros reenrollados para telas', max_digits=10, null=True),
        ),
    ]
