# Generated by Django 5.2.7 - Merge conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_loteproduccion_cantidad_metros'),
        ('gestion', '0035_revert_sp_sin_nro'),
    ]

    operations = [
    ]
