# Generated by Django 5.2.12 on 2026-03-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_merge_20260316_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestion.sede'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='gestion.sede'),
        ),
    ]
