# Generated by Cursor on 2026-03-17
#
# This migration fixes a prior SeparateDatabaseAndState migration (0039)
# that updated only Django's state but did not apply the actual DB schema
# changes on SQL Server. As a result, columns like `sede_id` were missing.
#
# We apply the DB operations only, without changing state (state already has
# these fields from 0039).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0039_cliente_sede_producto_sede_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        )
    ]

