# Generated by Django 5.2.7 on 2026-04-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_ordenproduccion_peso_neto_positivo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_object_fecha',
        ),
    ]
