# Generated by Django 5.2.9 on 2026-05-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_ordenproduccion_peso_neto_positivo'),
        ('gestion', '0053_merge_migrate_heads'),
    ]

    operations = [
    ]
