# Generated by Django 5.2.7 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_producto_unique_codigo_sede'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='cli_activo_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='cli_sede_activo_idx',
        ),
        migrations.RemoveIndex(
            model_name='loteproduccion',
            name='lote_hora_inicio_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_pagado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_vencimiento_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_fecha_pedido_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_cartera_vencida_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_cliente_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoventa',
            name='pv_sede_anulado_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc_cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formulacolor',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulacolor',
            name='nombre_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='codigo_lote',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('gr', 'Gramos (gr)'), ('lb', 'Libras (lb)'), ('l', 'Litros (l)'), ('ml', 'Mililitros (ml)'), ('gl', 'Galones (gl)'), ('metros', 'Metros (m)'), ('yardas', 'Yardas (yd)'), ('unidades', 'Unidades (u)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('nombre', 'sede')},
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('nombre', 'sede')},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('ruc_cedula', 'sede')},
        ),
        migrations.AlterUniqueTogether(
            name='formulacolor',
            unique_together={('codigo', 'sede'), ('nombre_color', 'sede')},
        ),
        migrations.AlterUniqueTogether(
            name='loteproduccion',
            unique_together={('codigo_lote', 'orden_produccion')},
        ),
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together={('nombre', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='ordenproduccion',
            unique_together={('codigo', 'sede')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('nombre', 'sede')},
        ),
        migrations.AddIndex(
            model_name='descargaquimicoop',
            index=models.Index(fields=['orden_produccion', 'estado'], name='gestion_des_orden_p_89a635_idx'),
        ),
        migrations.AddIndex(
            model_name='descargaquimicoop',
            index=models.Index(fields=['bodega', 'fecha_descarga'], name='gestion_des_bodega__d1cd25_idx'),
        ),
    ]
