# Generated by Django 5.2.7 on 2026-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0057_remove_cliente_cli_activo_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('hilo', 'Hilo'), ('tela', 'Tela'), ('subproducto', 'Subproducto'), ('quimico', 'Químico'), ('insumo', 'Insumo'), ('materia_prima', 'Materia prima')], max_length=20),
        ),
    ]
