# Generated by Django 5.2.7 on 2026-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='clasificacion_calidad',
            field=models.CharField(choices=[('primera', 'Primera Calidad'), ('segunda', 'Segunda Calidad'), ('saldo', 'Saldo / Retazo')], default='primera', max_length=50),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='peso_merma',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='tipo_merma',
            field=models.CharField(blank=True, choices=[('maquina', 'Falla Técnica / Máquina'), ('material', 'Calidad de Hilo / Material'), ('setup', 'Arranque / Setup'), ('corte', 'Corte / Empalme'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
