# Generated by Django 5.2.7 on 2026-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_loteproduccion_clasificacion_calidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=20),
        ),
    ]
