# Generated by Django 5.2.7 on 2026-06-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0060_ordenproduccion_prioridad'),
        ('gestion', '0064_backfill_producto_salida'),
    ]

    operations = [
    ]
