# Generated by Django 5.2.7 on 2026-06-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0065_merge_20260603_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='bodega_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_entrada', to='gestion.bodega', verbose_name='Bodega de Entrada'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='bodega_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_salida', to='gestion.bodega', verbose_name='Bodega de Salida'),
        ),
        migrations.AlterField(
            model_name='componentemezclaop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consumolotedetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='bodega_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_entrada', to='gestion.bodega', verbose_name='Bodega de Entrada (MP)'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='producto_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_como_entrada', to='gestion.producto', verbose_name='Producto de Entrada'),
        ),
    ]
