# Generated by Django 5.2.7 on 2026-06-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0069_costeo_lote_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprimalote',
            name='bodega_recepcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas_recibidas', to='gestion.bodega'),
        ),
    ]
