# Generated by Django 5.2.7 on 2026-06-11 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0070_alter_materiaprimalote_bodega_recepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden de ejecución (menor número = primero)')),
                ('tipo_flujo', models.CharField(choices=[('secuencial', 'Secuencial'), ('paralelo', 'Paralelo')], default='secuencial', max_length=20)),
                ('es_bloqueante', models.BooleanField(default=True, help_text='Si es True, los siguientes procesos esperan a que se complete')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='gestion.area')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.processstep')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('area', 'proceso')},
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccionSubproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_inicio_planificada', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si fue rechazado, incluir el motivo', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.areaprocessstep')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='gestion.ordenproduccion')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprocesos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['area_proceso__orden'],
                'indexes': [models.Index(fields=['orden_produccion', 'estado'], name='gestion_ord_orden_p_e30478_idx'), models.Index(fields=['usuario_responsable', 'estado'], name='gestion_ord_usuario_1d1c93_idx')],
                'unique_together': {('orden_produccion', 'area_proceso')},
            },
        ),
    ]
