# Generated by Django 5.2.7 on 2026-06-11 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0071_areaprocessstep_ordenproduccionsubproceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(help_text='Orden secuencial de ejecución (1, 2, 3...)')),
                ('tiempo_procesamiento_minutos', models.IntegerField(blank=True, help_text='Tiempo promedio estimado para esta etapa', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_produccion', to='gestion.area')),
                ('bodega_entrada', models.ForeignKey(help_text='Bodega de donde toma el material', on_delete=django.db.models.deletion.PROTECT, related_name='etapas_entrada', to='gestion.bodega')),
                ('bodega_salida', models.ForeignKey(help_text='Bodega donde deposita el resultado', on_delete=django.db.models.deletion.PROTECT, related_name='etapas_salida', to='gestion.bodega')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.maquina')),
            ],
            options={
                'verbose_name': 'Etapa de Producción',
                'verbose_name_plural': 'Etapas de Producción',
                'ordering': ['area', 'orden'],
                'unique_together': {('area', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_transferida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bodega_destino', models.ForeignKey(help_text='Bodega inicial del área destino (= MP para el área destino)', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='gestion.bodega')),
                ('bodega_origen', models.ForeignKey(help_text='Bodega final del área origen', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='gestion.bodega')),
                ('orden_area_destino', models.ForeignKey(help_text='Orden de producción que recibe el producto', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='gestion.ordenproduccion')),
                ('orden_area_origen', models.ForeignKey(help_text='Orden de producción que generó el producto', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='gestion.ordenproduccion')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia Interárea',
                'verbose_name_plural': 'Transferencias Interárea',
                'ordering': ['-fecha_transferencia'],
                'indexes': [models.Index(fields=['orden_area_origen', 'orden_area_destino'], name='gestion_tra_orden_a_b6a1b0_idx'), models.Index(fields=['fecha_transferencia'], name='gestion_tra_fecha_t_4fd6c0_idx')],
            },
        ),
    ]
