# Generated by Django 5.2.7 on 2026-06-23 19:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0072_etapaproduccion_transferenciainterarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.PositiveIntegerField(default=1, help_text='Orden secuencial de la transformación dentro de la OP (1, 2, 3...)')),
                ('peso_entrada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('peso_salida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('merma', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, help_text='Calculada automáticamente: peso_entrada - peso_salida', max_digits=12)),
                ('cantidad_entrada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cantidad_salida', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('rechazada', 'Rechazada')], db_index=True, default='completada', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(blank=True, help_text='Etapa planificada que ejecuta esta transformación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformaciones', to='gestion.etapaproduccion')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformaciones', to='gestion.maquina')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformaciones_operadas', to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones', to='gestion.ordenproduccion', verbose_name='Orden de Producción')),
                ('producto_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformaciones_como_entrada', to='gestion.producto', verbose_name='Producto que entra a la máquina')),
                ('producto_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformaciones_como_salida', to='gestion.producto', verbose_name='Producto que sale de la máquina (nuevo código)')),
            ],
            options={
                'verbose_name': 'Transformación de Producto',
                'verbose_name_plural': 'Transformaciones de Producto',
                'ordering': ['orden_produccion', 'numero_secuencia'],
                'indexes': [models.Index(fields=['orden_produccion', 'numero_secuencia'], name='gestion_tra_orden_p_d4ae0b_idx'), models.Index(fields=['maquina', 'fecha_creacion'], name='gestion_tra_maquina_b1e396_idx')],
                'constraints': [models.UniqueConstraint(fields=('orden_produccion', 'numero_secuencia'), name='transf_unica_por_secuencia_en_op'), models.CheckConstraint(condition=models.Q(('peso_entrada__gte', 0), ('peso_salida__gte', 0)), name='gestion_transformacion_pesos_no_negativos')],
            },
        ),
    ]
