# Generated by Django 5.2.7 on 2026-07-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0073_transformacion_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_produccion', to='gestion.area')),
                ('maquinas', models.ManyToManyField(blank=True, related_name='lineas_produccion', to='gestion.maquina')),
            ],
            options={
                'verbose_name': 'Línea de Producción',
                'verbose_name_plural': 'Líneas de Producción',
                'ordering': ['area', 'nombre'],
                'unique_together': {('nombre', 'area')},
            },
        ),
    ]
