# Generated by Django 5.2.7 on 2026-07-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0074_lineaproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ORIGINAL', 'Original'), ('REIMPRESION', 'Reimpresión Idéntica'), ('REETIQUETADO', 'Reetiquetado con Cambio')], max_length=20)),
                ('secuencia', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, choices=[('DANIADA', 'Etiqueta Dañada'), ('PERDIDA', 'Etiqueta Perdida'), ('ATASCO', 'Atasco de Impresora'), ('CORRECCION_PESO', 'Corrección de Peso'), ('RECLASIFICACION', 'Reclasificación de Calidad'), ('REEMPAQUE', 'Reempaque'), ('OTRO', 'Otro')], max_length=30, null=True)),
                ('detalle_motivo', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datos_snapshot', models.JSONField()),
                ('formato', models.CharField(choices=[('ZPL', 'ZPL Zebra'), ('PDF', 'PDF Universal')], default='ZPL', max_length=3)),
                ('anulada', models.BooleanField(default=False)),
                ('anula_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulada_por', to='gestion.eventoetiqueta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='gestion.loteproduccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_etiqueta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lote', 'secuencia'],
                'indexes': [models.Index(fields=['timestamp'], name='gestion_eve_timesta_ddb9c2_idx'), models.Index(fields=['lote', 'secuencia'], name='gestion_eve_lote_id_25252e_idx')],
                'unique_together': {('lote', 'secuencia')},
            },
        ),
    ]
