"""
Django settings for TexCore project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import logging
import os
from django.core.exceptions import ImproperlyConfigured

def get_env_variable(var_name):
    """Obtiene la variable de entorno o lanza una excepción (Fail Fast)."""
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = f"Falta la variable de entorno obligatoria: {var_name}"
        raise ImproperlyConfigured(error_msg)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Acepta: 1, true, yes (case-insensitive). Cualquier otro valor = False.
DEBUG = os.environ.get('DEBUG', '0').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # JWT Blacklist (requiere migrate)
    'corsheaders',
    'drf_spectacular',  # Documentación OpenAPI 3.1 en /api/docs/
    # Local Apps (GestionConfig carga las señales de auditoría en ready())
    'gestion.apps.GestionConfig',
    'inventory.apps.InventoryConfig',
]

# Security & Middleware
APPEND_SLASH = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Added for CORS
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gestion.middleware.AuditMiddleware',
]

# CORS Configuration - Strict
CORS_ALLOWED_ORIGINS_ENV = get_env_variable('CORS_ALLOWED_ORIGINS')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins - Strict
CSRF_TRUSTED_ORIGINS_ENV = get_env_variable('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',')]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


ROOT_URLCONF = 'TexCore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TexCore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {
            'driver': os.environ.get('DB_DRIVER'),
            'extra_params': 'Encrypt=yes;TrustServerCertificate=yes'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    d for d in [
        os.path.join(BASE_DIR, 'frontend', 'dist'),
    ] if os.path.exists(d)
]

STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'gestion.auth_backends.CookieJWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'gestion.exceptions.texcore_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TexCore API',
    'DESCRIPTION': 'Sistema Integral de Gestión Textil — API REST',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Solo exponer docs en DEBUG — en producción requiere autenticación
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    # Custom settings for cookie-based auth
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_DOMAIN': None,
    'AUTH_COOKIE_SECURE': not DEBUG,  # True in production (when DEBUG=False)
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

# Custom User Model
AUTH_USER_MODEL = 'gestion.CustomUser'

# ---------------------------------------------------------------------------
# Logging — RFC 5424 (IETF Syslog Protocol)
# Facility 16 (local0) reservado para el backend Django principal.
# Todos los loggers del proyecto emiten mensajes con el formato:
#   <PRI>1 TIMESTAMP HOSTNAME APP-NAME PROCID MSGID [SD-ELEMENT] MSG
# ---------------------------------------------------------------------------

from TexCore.logging_rfc5424 import RFC5424Formatter as _RFC5424Formatter

# Directorio de logs — se crea en arranque si no existe
_LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(_LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Formatter principal — RFC 5424 Syslog
        'rfc5424': {
            '()': _RFC5424Formatter,
            'facility': 16,   # local0 — backend Django
            'app_name': 'texcore-backend',
        },
        # Fallback legible para desarrollo local (DEBUG=True)
        'verbose': {
            'format': '{levelname} {asctime} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        # stdout → recogido por Docker / systemd journal en producción
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'rfc5424' if not DEBUG else 'verbose',
        },
        # Archivo rotante — RFC 5424 en producción, verbose en dev
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(_LOGS_DIR, 'backend.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB por archivo
            'backupCount': 5,
            'formatter': 'rfc5424',
            'encoding': 'utf-8',
        },
        # SysLogHandler — solo activo si /dev/log existe (Linux / Docker)
        **({
            'syslog': {
                'level': 'WARNING',
                'class': 'logging.handlers.SysLogHandler',
                'address': '/dev/log',
                'facility': 'local0',
                'formatter': 'rfc5424',
            }
        } if os.path.exists('/dev/log') else {}),
    },
    'loggers': {
        # App de gestión — todos los niveles a archivo + consola
        'gestion': {
            'handlers': ['console', 'file'] + (['syslog'] if os.path.exists('/dev/log') else []),
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # App de inventario / MRP
        'inventory': {
            'handlers': ['console', 'file'] + (['syslog'] if os.path.exists('/dev/log') else []),
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Django core — solo WARNING y superior
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Errores HTTP — siempre a archivo y syslog
        'django.request': {
            'handlers': ['console', 'file'] + (['syslog'] if os.path.exists('/dev/log') else []),
            'level': 'ERROR',
            'propagate': False,
        },
        # ORM queries — solo en modo DEBUG para evitar flood
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
    },
}

