# Generated by Django 5.2.7 on 2025-11-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0007_ordenproduccion_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='gestion.bodega')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='gestion.chemical')),
            ],
            options={
                'verbose_name': 'Stock de Insumo',
                'verbose_name_plural': 'Stock de Insumos',
                'unique_together': {('bodega', 'chemical')},
            },
        ),
    ]
