# Generated by Django 5.2.9 on 2025-12-15 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_movimiento', models.CharField(choices=[('COMPRA', 'Compra de Material'), ('PRODUCCION', 'Entrada por Producción'), ('TRANSFERENCIA', 'Transferencia entre Bodegas'), ('AJUSTE', 'Ajuste de Inventario'), ('VENTA', 'Salida por Venta'), ('DEVOLUCION', 'Devolución de Cliente'), ('CONSUMO', 'Consumo para Producción')], db_index=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento_ref', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_destino', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='gestion.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='gestion.bodega')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.loteproduccion')),
                ('producto', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='gestion.bodega')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='gestion.loteproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='gestion.producto')),
            ],
            options={
                'verbose_name': 'Stock en Bodega',
                'verbose_name_plural': 'Stock en Bodegas',
                'unique_together': {('bodega', 'producto', 'lote')},
            },
        ),
    ]
