# Generated by Django 5.2.7 on 2026-08-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_pedidoventa_estado'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallehistorialdespacho',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_historial_despacho', to='gestion.pedidoventa'),
        ),
    ]
