# Generated by Django 5.2.11 on 2026-02-06 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='editado',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento ha sido editado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_ultima_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última edición', null=True),
        ),
        migrations.CreateModel(
            name='AuditoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campo_modificado', models.CharField(help_text='Nombre del campo que fue modificado', max_length=50)),
                ('valor_anterior', models.TextField(help_text='Valor antes de la modificación')),
                ('valor_nuevo', models.TextField(help_text='Valor después de la modificación')),
                ('razon_cambio', models.TextField(blank=True, help_text='Justificación del cambio')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='inventory.movimientoinventario')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Movimiento',
                'verbose_name_plural': 'Auditorías de Movimientos',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['movimiento', '-fecha_modificacion'], name='inventory_a_movimie_1bd024_idx')],
            },
        ),
    ]
