# Generated by Django 5.2.11 on 2026-02-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientoinventario_editado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
