# Generated by Django 5.2.7 on 2026-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_detallepedido_cantidad_fabricada_and_more'),
        ('inventory', '0002_detallehistorialdespacho_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbodega',
            name='stock_comprometido',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Cantidad reservada exclusivamente para pedidos comerciales (MTO)', max_digits=12, verbose_name='Stock Comprometido / Reservado'),
        ),
        migrations.AddConstraint(
            model_name='stockbodega',
            constraint=models.CheckConstraint(condition=models.Q(('stock_comprometido__gte', 0)), name='chk_stockbodega_comprometido_nonneg'),
        ),
    ]
