# Generated by Django 5.2.11 on 2026-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_pagocliente'),
        ('inventory', '0003_alter_movimientoinventario_saldo_resultante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockbodega',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stockbodega',
            constraint=models.UniqueConstraint(condition=models.Q(('lote__isnull', True)), fields=('bodega', 'producto'), name='inventory_stockbodega_unique_without_lote'),
        ),
        migrations.AddConstraint(
            model_name='stockbodega',
            constraint=models.UniqueConstraint(condition=models.Q(('lote__isnull', False)), fields=('bodega', 'producto', 'lote'), name='inventory_stockbodega_unique_with_lote'),
        ),
    ]
