# Generated by Django 5.2.11 on 2026-02-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_pagocliente'),
        ('inventory', '0004_fix_unique_constraint_with_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbodega',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='gestion.loteproduccion'),
        ),
    ]
