# Generated by Django 5.2.11 on 2026-02-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_movimientoinventario_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario_aprobador',
        ),
    ]
