# Generated by Django 5.2.7 on 2026-02-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_movimientoinventario_estado_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_GetStockBodegaReport
                @BodegaID INT
            AS
            BEGIN
                SET NOCOUNT ON;

                SELECT 
                    p.codigo AS codigo_producto,
                    p.descripcion AS descripcion_producto,
                    p.unidad_medida,
                    ISNULL(l.codigo_lote, 'N/A') AS lote,
                    SUM(sb.cantidad) AS stock_actual
                FROM inventory_stockbodega sb
                INNER JOIN gestion_producto p ON p.id = sb.producto_id
                LEFT JOIN gestion_loteproduccion l ON l.id = sb.lote_id
                WHERE sb.bodega_id = @BodegaID
                GROUP BY 
                    p.codigo,
                    p.descripcion,
                    p.unidad_medida,
                    l.codigo_lote
                HAVING SUM(sb.cantidad) > 0
                ORDER BY p.descripcion ASC;
            END
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_GetStockBodegaReport"
        )
    ]
