# Generated by Django 5.2.7 on 2026-02-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stock_bodega_report_sp'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER PROCEDURE sp_GetKardexBodega
                @BodegaID INT,
                @ProductoID INT
            AS
            BEGIN
                SET NOCOUNT ON;

                SELECT 
                    m.id,
                    CONVERT(VARCHAR(19), m.fecha, 120) AS fecha,
                    m.tipo_movimiento,
                    m.documento_ref,
                    m.cantidad,
                    m.saldo_resultante,
                    m.bodega_origen_id,
                    m.bodega_destino_id
                FROM inventory_movimientoinventario m
                WHERE m.producto_id = @ProductoID
                  AND (m.bodega_origen_id = @BodegaID OR m.bodega_destino_id = @BodegaID)
                ORDER BY m.fecha ASC;
            END
            """,
            reverse_sql="""
            ALTER PROCEDURE sp_GetKardexBodega
                @BodegaID INT,
                @ProductoID INT
            AS
            BEGIN
                SET NOCOUNT ON;

                SELECT 
                    m.id,
                    m.fecha,
                    m.tipo_movimiento,
                    m.documento_ref,
                    m.cantidad,
                    m.saldo_resultante,
                    m.bodega_origen_id,
                    m.bodega_destino_id
                FROM inventory_movimientoinventario m
                WHERE m.producto_id = @ProductoID
                  AND (m.bodega_origen_id = @BodegaID OR m.bodega_destino_id = @BodegaID)
                ORDER BY m.fecha ASC;
            END
            """
        )
    ]
