# Generated by Django 5.2.12 on 2026-03-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_detallepedido_subtotal_detallepedido_total_con_iva_and_more'),
        ('inventory', '0013_update_kardex_sp_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHistorialDespachoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Historial de Despacho del Pedido',
            },
        ),
        migrations.RemoveField(
            model_name='historialdespacho',
            name='pedidos_ids',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_origen', 'fecha'], include=('producto', 'cantidad', 'saldo_resultante'), name='idx_mov_bodega_fecha_incl'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='inventory_movimientoinventario_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_resultante__gte', 0)), name='inventory_movimientoinventario_saldo_positivo'),
        ),
        migrations.AddField(
            model_name='detallehistorialdespachopedido',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.historialdespacho'),
        ),
        migrations.AddField(
            model_name='detallehistorialdespachopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.pedidoventa'),
        ),
        migrations.AddField(
            model_name='historialdespacho',
            name='pedidos',
            field=models.ManyToManyField(through='inventory.DetalleHistorialDespachoPedido', to='gestion.pedidoventa'),
        ),
    ]
