# Generated by Django 5.2.12 on 2026-03-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_remove_formulacolor_productos_auditlog_fasereceta_and_more'),
        ('inventory', '0014_detallehistorialdespachopedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.DecimalField(decimal_places=3, help_text='Cantidad sugerida a comprar (Requerimiento - Stock Actual)', max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Convertida en OC'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede')),
            ],
            options={
                'verbose_name': 'Orden de Compra Sugerida',
                'verbose_name_plural': 'Órdenes de Compra Sugeridas',
                'unique_together': {('producto', 'sede', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origen_tipo', models.CharField(choices=[('PEDIDO', 'Pedido de Venta'), ('OP', 'Orden de Producción')], max_length=20)),
                ('origen_id', models.PositiveIntegerField(help_text='ID del Pedido o de la OP que genera este requerimiento')),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('producto_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='gestion.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede')),
            ],
            options={
                'verbose_name': 'Requerimiento de Material',
                'verbose_name_plural': 'Requerimientos de Materiales',
                'indexes': [models.Index(fields=['sede', 'producto_requerido'], name='inventory_r_sede_id_ab1ed1_idx')],
            },
        ),
    ]
