# Generated by Django 5.2.12 on 2026-03-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_ordencomprasugerida_requerimientomaterial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE PROCEDURE sp_GetStockAgrupadoPorSede
                @SedeID INT
            AS
            BEGIN
                SET NOCOUNT ON;

                SELECT 
                    s.producto_id,
                    SUM(s.cantidad) AS total_stock
                FROM inventory_stockbodega s
                INNER JOIN gestion_bodega b ON s.bodega_id = b.id
                WHERE b.sede_id = @SedeID
                GROUP BY s.producto_id;
            END
            """,
            reverse_sql="DROP PROCEDURE sp_GetStockAgrupadoPorSede"
        ),
    ]
