# Generated by Django 5.2.7 on 2026-04-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_sp_stock_cero_bodega'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='idx_mov_tipo_fecha',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='idx_mov_producto_fecha',
        ),
    ]
