# Generated by Django 5.2.7 on 2026-04-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_produccion_reporting_sps'),
        ('inventory', '0022_sp_get_inventario_aging_bucket_filter'),
    ]

    operations = [
    ]
