# Generated by Django 5.2.7 on 2026-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_merge_20260415_1345'),
        ('inventory', '0023_merge_20260421_1448'),
    ]

    operations = [
    ]
