# Generated by Django 5.2.7 on 2026-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_fix_produccion_reporting_sps_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('COMPRA', 'Compra de Material'), ('PRODUCCION', 'Entrada por Producción'), ('TRANSFERENCIA', 'Transferencia entre Bodegas'), ('AJUSTE', 'Ajuste de Inventario'), ('VENTA', 'Salida por Venta'), ('DEVOLUCION', 'Devolución de Cliente'), ('CONSUMO', 'Consumo para Producción'), ('MERMA', 'Merma / Desperdicio')], db_index=True, max_length=20),
        ),
    ]
