// Lista de países en español, usada como catálogo estático para selects
// de "país de origen" en el módulo de bodega/catálogo. No existía ninguna
// fuente de países en el proyecto (ni librería ni constante) — se agrega
// aquí para reutilizarse en cualquier selector de país.
export const PAISES: string[] = [
  'Ecuador',
  'Colombia',
  'Perú',
  'Bolivia',
  'Chile',
  'Argentina',
  'Brasil',
  'Uruguay',
  'Paraguay',
  'Venezuela',
  'Panamá',
  'Costa Rica',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'República Dominicana',
  'Cuba',
  'México',
  'Estados Unidos',
  'Canadá',
  'España',
  'Portugal',
  'Alemania',
  'Francia',
  'Italia',
  'Reino Unido',
  'China',
  'India',
  'Japón',
  'Corea del Sur',
  'Taiwán',
  'Vietnam',
  'Indonesia',
  'Turquía',
  'Pakistán',
  'Bangladesh',
];
